"""Layer P report writer. Every number that is a claim carries a 90% HDI (A-7)."""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd

from ambo.baselines import OLSResult
from ambo.config import CHANNEL_IDS, CHANNEL_LABELS, REPORTS_DIR
from ambo.evaluate import RecoveryResult
from ambo.optimize import Allocation
from ambo.plots.theme import apply_theme, tokens


def write_recovery_report(
    recovery: RecoveryResult,
    holdout: pd.DataFrame,
    ols: OLSResult,
    allocation: Allocation,
    *,
    revenue_mean: float,
    output_dir: Path | None = None,
) -> Path:
    out = Path(output_dir) if output_dir is not None else REPORTS_DIR / "recovery"
    out.mkdir(parents=True, exist_ok=True)
    _write_roas_plot(recovery, out / "roas_P.png")
    markdown = _render(recovery, holdout, ols, allocation, revenue_mean)
    dest = out / "RECOVERY_REPORT.md"
    dest.write_text(markdown, encoding="utf-8")
    payload = {
        "gates": recovery.gates,
        "gate_detail": recovery.gate_detail,
        "all_green": all(recovery.gates.values()),
        "spearman": recovery.spearman,
        "media_share_delta": recovery.media_share_delta,
        "channels": [
            {
                "channel": row.channel,
                "true_avg_roas": row.true_avg_roas,
                "roas_median": row.roas_median,
                "roas_hdi_low": row.roas_hdi_low,
                "roas_hdi_high": row.roas_hdi_high,
                "in_hdi": row.in_hdi,
                "mae_pct": row.mae_pct,
            }
            for row in recovery.channels
        ],
        "holdout": {
            "model_mape": float(holdout["model_mape"].iloc[0]),
            "naive_mape": float(holdout["naive_mape"].iloc[0]),
            "coverage_90": float(holdout["coverage_90"].iloc[0]),
        },
        "optimizer": {
            "spends": allocation.spends,
            "gain_mean": allocation.gain_vs_historical,
            "gain_hdi_low": allocation.gain_hdi[0],
            "gain_hdi_high": allocation.gain_hdi[1],
            "expected_contribution": allocation.expected_contribution,
            "contribution_hdi": list(allocation.contribution_hdi),
        },
    }
    (out / "metrics_P.json").write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return dest


def write_ssot(
    recovery: RecoveryResult, holdout: pd.DataFrame, allocation: Allocation, revenue_mean: float
) -> Path:
    dest = REPORTS_DIR / "NUMERIC_SSOT.md"
    dest.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# NUMERIC_SSOT",
        "",
        "Generated by `python -m ambo.run layer_p`. Do not hand-edit.",
        "",
        "| Key | Value | 90% HDI |",
        "|---|---:|---|",
    ]
    for row in recovery.channels:
        hdi = f"[{row.roas_hdi_low:.2f}, {row.roas_hdi_high:.2f}]"
        lines.append(f"| roas_{row.channel}_median | {row.roas_median:.3f} | {hdi} |")
    mape = float(holdout["model_mape"].iloc[0])
    naive = float(holdout["naive_mape"].iloc[0])
    cov = float(holdout["coverage_90"].iloc[0])
    lines.append(f"| holdout_model_mape | {mape:.4f} | — |")
    lines.append(f"| holdout_naive_mape | {naive:.4f} | — |")
    lines.append(f"| holdout_coverage_90 | {cov:.3f} | — |")
    gain_pct = 100.0 * allocation.gain_vs_historical / revenue_mean
    gain_lo = 100.0 * allocation.gain_hdi[0] / revenue_mean
    gain_hi = 100.0 * allocation.gain_hdi[1] / revenue_mean
    lines.append(
        f"| expected_gain_pct_vs_historical | {gain_pct:.2f} | [{gain_lo:.2f}, {gain_hi:.2f}] |"
    )
    lines.append(f"| recovery_all_green | {str(all(recovery.gates.values())).lower()} | — |")
    lines.append("")
    dest.write_text("\n".join(lines), encoding="utf-8")
    return dest


def _write_roas_plot(recovery: RecoveryResult, path: Path) -> None:
    apply_theme()
    import matplotlib.pyplot as plt

    color = tokens()
    names = [CHANNEL_LABELS[row.channel] for row in recovery.channels]
    med = [row.roas_median for row in recovery.channels]
    lo = [row.roas_hdi_low for row in recovery.channels]
    hi = [row.roas_hdi_high for row in recovery.channels]
    truth = [row.true_avg_roas for row in recovery.channels]
    y = np.arange(len(names))
    fig, ax = plt.subplots(figsize=(8, 4.5))
    ax.hlines(y, lo, hi, color=color["mid"], linewidth=1)
    ax.plot(med, y, "o", color=color["ink"], label="posterior median")
    ax.plot(truth, y, "x", color=color["accent-01"], markersize=8, label="true average ROAS")
    ax.set_yticks(y)
    ax.set_yticklabels(names)
    ax.set_xlabel("Average ROAS")
    ax.set_title("Layer P recovery: true ROAS vs 90% HDI")
    ax.legend()
    fig.tight_layout()
    fig.savefig(path, dpi=120)
    plt.close(fig)


def _render(
    recovery: RecoveryResult,
    holdout: pd.DataFrame,
    ols: OLSResult,
    allocation: Allocation,
    revenue_mean: float,
) -> str:
    verdict = "all-green" if all(recovery.gates.values()) else "RED"
    rows = ["| Gate | Result | Detail |", "|---|---|---|"]
    for name, passed in recovery.gates.items():
        mark = "PASS" if passed else "FAIL"
        rows.append(f"| {name} | {mark} | {recovery.gate_detail[name]} |")
    ch_lines = [
        "| Channel | True ROAS | Posterior median | 90% HDI | In HDI | curve MAE% |",
        "|---|---:|---:|---|:---:|---:|",
    ]
    for row in recovery.channels:
        hdi = f"[{row.roas_hdi_low:.2f}, {row.roas_hdi_high:.2f}]"
        ch_lines.append(
            f"| `{row.channel}` | {row.true_avg_roas:.2f} | {row.roas_median:.2f} | {hdi} | "
            f"{'yes' if row.in_hdi else 'no'} | {row.mae_pct:.1f} |"
        )
    mape = float(holdout["model_mape"].iloc[0])
    naive = float(holdout["naive_mape"].iloc[0])
    cov = float(holdout["coverage_90"].iloc[0])
    beats = "yes" if mape < naive else "no"
    ols_lines = [
        "| Channel | OLS coef | HC1 se | Bayesian median ROAS | same sign |",
        "|---|---:|---:|---:|:---:|",
    ]
    for channel in CHANNEL_IDS:
        coef = ols.coef[f"adstock_{channel}"]
        se = ols.se_hc1[f"adstock_{channel}"]
        roas = ols.bayesian_roas_median.get(channel, float("nan"))
        same = "yes" if ols.sign_stable.get(channel) else "no"
        ols_lines.append(f"| `{channel}` | {coef:.3f} | {se:.3f} | {roas:.3f} | {same} |")
    gain_pct = 100.0 * allocation.gain_vs_historical / revenue_mean
    gain_lo = 100.0 * allocation.gain_hdi[0] / revenue_mean
    gain_hi = 100.0 * allocation.gain_hdi[1] / revenue_mean
    alloc_lines = [
        "| Channel | Historical €/wk | Optimal €/wk | Binding 1.3× cap |",
        "|---|---:|---:|:---:|",
    ]
    for channel in CHANNEL_IDS:
        hist = allocation.historical[channel]
        opt = allocation.spends[channel]
        bind = "yes" if allocation.binding[channel] else "no"
        alloc_lines.append(f"| `{channel}` | {hist:.0f} | {opt:.0f} | {bind} |")
    closing = (
        "This recovery suite shows that the raw-PyMC MMM recovers disclosed simulator "
        "truth it was never shown. Recovery is gated on ROAS and response-curve shape at "
        "observed spend, not on point recovery of Hill K and s. The simulator uses raw "
        "geometric recursion; the model uses a truncated convolution with MD-020 "
        "normalised weights (steady-state adstock of a constant weekly allocation "
        "equals the allocation itself; DC-201) — agreement is evidence rather than a "
        "circular identity. Layer R (real agency data) is not in this repository; "
        "Charter §7 degradation applies (ADR-012). The optimiser result is an in-sample "
        "counterfactual under the fitted model: response curves are assumed to hold and "
        "competitors do not react. No channel is pushed beyond 1.3× its historically "
        "observed weekly spend. Platform-reported conversions remain the object of the "
        "attribution-gap comparison, never a calibration target."
    )
    return "\n".join(
        [
            "# Recovery report",
            "",
            "> Generated by `python -m ambo.run layer_p` from the Layer P posterior.",
            "> Do not hand-edit.",
            "",
            "## Verdict",
            "",
            f"Five-channel Layer P (156 weeks, seed 101): **{verdict}**.",
            "",
            "## Gate table",
            "",
            *rows,
            "",
            "## ROAS recovery",
            "",
            "True average ROAS is ×; posterior median is a dot with 90% HDI whiskers.",
            "",
            "![roas_P.png](roas_P.png)",
            "",
            *ch_lines,
            "",
            "## Holdout",
            "",
            f"Weeks 131–156, conditional on actual spend. Model MAPE {mape:.4f} vs seasonal-naive "
            f"{naive:.4f} (beats naive: {beats}). 90% coverage {cov:.3f}.",
            "",
            "## OLS baseline",
            "",
            "OLS+HC1 with adstock fixed at the prior-mode λ and no Hill. "
            "Signs ship as they are (VR-601).",
            "",
            *ols_lines,
            "",
            "## Budget reallocation (Layer P, Charter §7)",
            "",
            "Expected weekly media-contribution gain vs historical mix: "
            f"{allocation.gain_vs_historical:.0f} € "
            f"(90% HDI [{allocation.gain_hdi[0]:.0f}, {allocation.gain_hdi[1]:.0f}]), "
            f"{gain_pct:.2f}% of mean weekly revenue (90% HDI [{gain_lo:.2f}, {gain_hi:.2f}]). "
            "Steady-state adstock of a constant weekly allocation equals the allocation "
            "itself (MD-020 normalised weights; DC-201).",
            "",
            *alloc_lines,
            "",
            "## What this does and does not prove",
            "",
            closing,
            "",
        ]
    )


def write_attribution_gap(
    sim_media: pd.DataFrame, recovery: RecoveryResult, output_dir: Path | None = None
) -> Path:
    """Platform ROAS vs MMM incremental ROAS (DC-501). Offline channels omitted."""
    out = Path(output_dir) if output_dir is not None else REPORTS_DIR / "decide"
    out.mkdir(parents=True, exist_ok=True)
    by_ch = {row.channel: row for row in recovery.channels}
    records = []
    for channel, row in by_ch.items():
        slice_ = sim_media.loc[sim_media["channel"] == channel]
        plat = pd.to_numeric(slice_["platform_revenue_eur"], errors="coerce").sum()
        spend = float(pd.to_numeric(slice_["spend_eur"], errors="coerce").sum())
        if spend <= 0 or pd.isna(plat):
            continue
        platform_roas = float(plat) / spend
        records.append(
            {
                "channel": channel,
                "platform_roas": platform_roas,
                "mmm_roas_median": row.roas_median,
                "mmm_hdi_low": row.roas_hdi_low,
                "mmm_hdi_high": row.roas_hdi_high,
                "overcredit_ratio": platform_roas / row.roas_median
                if row.roas_median
                else float("nan"),
            }
        )
    frame = pd.DataFrame(records)
    frame.to_csv(out / "attribution_gap.csv", index=False, lineterminator="\n")
    _write_gap_plot(frame, out / "dc_attribution_gap.png")
    return out / "attribution_gap.csv"


def _write_gap_plot(frame: pd.DataFrame, path: Path) -> None:
    if frame.empty:
        return
    apply_theme()
    import matplotlib.pyplot as plt

    color = tokens()
    y = np.arange(len(frame))
    fig, ax = plt.subplots(figsize=(8, 3.5))
    ax.hlines(y, frame["mmm_hdi_low"], frame["mmm_hdi_high"], color=color["mid"], linewidth=1)
    ax.plot(frame["mmm_roas_median"], y, "o", color=color["ink"], label="MMM median")
    ax.plot(frame["platform_roas"], y, "D", color=color["accent-01"], label="platform")
    ax.set_yticks(y)
    ax.set_yticklabels([CHANNEL_LABELS[c] for c in frame["channel"]])
    ax.set_xlabel("ROAS")
    ax.set_title("Attribution gap: platform vs MMM (90% HDI)")
    ax.legend()
    fig.tight_layout()
    fig.savefig(path, dpi=120)
    plt.close(fig)
