-- ad041_value_ranges: AD-041 range checks on fct_mmm_input. Singular test -- zero
-- rows returned = pass, any row returned = fail. Each failing row carries a `rule`
-- label naming which predicate it broke, so a failure output names the offending
-- rule directly (SPEC-03 section 4 AD-041: spend >= 0, revenue > 0, promo_flag in
-- (0,1)). promo_flag's own accepted_values generic test already covers that half
-- of AD-041 in `_fct_mmm_input__schema.yml`; this file covers the revenue and spend
-- range halves that a generic test cannot express.
--
-- The seven spend predicates are generated by a jinja loop over
-- var('channel_taxonomy') -- never hand-written per-channel SQL, matching the
-- model's own pivot discipline.
select week_start, layer, 'revenue_not_positive' as rule, revenue as offending_value
from {{ ref('fct_mmm_input') }}
where revenue <= 0

{% for channel in var('channel_taxonomy') %}
union all

select
    week_start,
    layer,
    'spend_{{ channel }}_negative' as rule,
    spend_{{ channel }} as offending_value
from {{ ref('fct_mmm_input') }}
where spend_{{ channel }} < 0
{% endfor %}
