-- ad042_revenue_reconciliation: AD-042 reconciliation across all three Layer P
-- layers (D-12). Singular test -- zero rows returned = pass, any row returned =
-- fail. Uses an absolute-difference tolerance, never float equality and never
-- equality after rounding (rounding can mask a real drift smaller than the
-- rounding unit but larger than 1e-6).
--
-- The CSV side reads through var('data_synthetic_path'), so this test travels
-- with the poisoned and fixture trees automatically -- the reconciliation is
-- against whatever tree the build was pointed at, not against a hard-coded path.
-- The three union branches are generated by a jinja loop over the same
-- scenario/layer pair list raw_outcome_p.sql established -- never hand-written.
{% set scenario_layers = [
    ("s_a", "P-SA"),
    ("s_b", "P-SB"),
    ("s_c", "P-SC"),
] %}

with mart_totals as (
    select layer, sum(revenue) as mart_revenue
    from {{ ref('fct_mmm_input') }}
    where layer in ({% for _, layer in scenario_layers %}'{{ layer }}'{{ ", " if not loop.last }}{% endfor %})
    group by layer
),

csv_totals as (
    {% for scenario_dir, layer in scenario_layers %}
    select '{{ layer }}' as layer, sum(revenue_eur) as csv_revenue
    from read_csv_auto('{{ var("data_synthetic_path") }}/{{ scenario_dir }}/outcome_weekly.csv')
    {% if not loop.last %}
    union all
    {% endif %}
    {% endfor %}
)

select
    mart_totals.layer,
    mart_totals.mart_revenue,
    csv_totals.csv_revenue,
    abs(mart_totals.mart_revenue - csv_totals.csv_revenue) as delta
from mart_totals
inner join csv_totals using (layer)
where abs(mart_totals.mart_revenue - csv_totals.csv_revenue) > 1e-6
