-- channels_present_both_directions: D-14's both-directions singular test. This
-- makes the absent-versus-ineffective distinction a build-time checked fact, so a
-- pivot bug that leaks one layer's spend into a column that layer does not own
-- fails at `dbt build` rather than surfacing later at model-fit time. It also gives
-- AD-044 (plan 03-06) a working shape to inherit at M4, when a real intake manifest
-- replaces stg_media_weekly's source-row presence as the thing being checked
-- against.
--
-- One file with two directions, each carrying a `direction` label, rather than two
-- separate test files: a pivot bug typically trips both directions at once, and
-- seeing both failure sets in one test's output is better debugging ergonomics --
-- the same reasoning D-10 applies to db.py's collect-all-raise-once (03-RESEARCH.md
-- Pattern 5, 03-CONTEXT.md D-14 Claude's Discretion).
--
-- Direction 1 (listed_without_source_rows): every channel dim_layer.channels_present
-- claims present for a layer must have at least one row in stg_media_weekly for that
-- layer. Splits the comma-joined string and anti-joins against the source relation.
with listed as (
    select
        dim_layer.layer,
        unnest(string_split(dim_layer.channels_present, ',')) as channel
    from {{ ref('dim_layer') }} as dim_layer
    where dim_layer.channels_present <> ''
),

direction_1 as (
    select
        'listed_without_source_rows' as direction,
        listed.layer,
        listed.channel,
        cast(null as date) as week_start,
        cast(null as double) as value
    from listed
    left join {{ ref('stg_media_weekly') }} as media
        on listed.layer = media.layer and listed.channel = media.channel
    where media.layer is null
),

-- Direction 2 (unlisted_channel_has_spend): every channel NOT listed in a layer's
-- channels_present must have an exactly-zero spend_<channel> column on every
-- fct_mmm_input row for that layer. Generated by a jinja loop over
-- var('channel_taxonomy') -- one union branch per channel -- so a taxonomy change
-- automatically gets a matching check with no hand-maintained per-channel branch
-- list. Membership is checked with `list_contains` over the comma-split list, a
-- whole-token match -- never a substring search, so 'search_brand' cannot be
-- mistaken for a prefix of another taxonomy entry.
direction_2 as (
    {% for channel in var('channel_taxonomy') %}
    select
        'unlisted_channel_has_spend' as direction,
        fct.layer,
        '{{ channel }}' as channel,
        fct.week_start,
        fct.spend_{{ channel }} as value
    from {{ ref('fct_mmm_input') }} as fct
    inner join {{ ref('dim_layer') }} as dim_layer
        on fct.layer = dim_layer.layer
    where
        not list_contains(string_split(dim_layer.channels_present, ','), '{{ channel }}')
        and fct.spend_{{ channel }} <> 0.0
    {{ "union all" if not loop.last }}
    {% endfor %}
)

select * from direction_1
union all
select * from direction_2
