-- fct_mmm_input: the single model input contract (AD-030), grain week x layer.
-- Materialized as a table (dbt_project.yml `marts: +materialized: table`); contract
-- enforced by `_fct_mmm_input__schema.yml` (T-03-04).
--
-- media_pivot: one aggregate spend_<channel> column per taxonomy entry, generated by
-- a jinja loop over `var('channel_taxonomy')` -- never hand-written per-channel SQL,
-- so the taxonomy var stays the single home for channel identity (03-RESEARCH.md).
with media_pivot as (
    select
        week_start,
        layer,
        {% for channel in var('channel_taxonomy') %}
        coalesce(sum(case when channel = '{{ channel }}' then spend end), 0.0)
            as spend_{{ channel }}{{ "," if not loop.last }}
        {% endfor %}
    from {{ ref('stg_media_weekly') }}
    group by week_start, layer
),

-- base: outcome drives the grain (one row per week x layer that has an outcome) --
-- inner-joined to promo and calendar (both are grain-complete for every outcome
-- week x layer), left-joined to media_pivot so a week with an outcome but no media
-- rows still gets seven zero-valued spend columns rather than NULLs.
base as (
    select
        outcome.week_start,
        outcome.layer,
        outcome.revenue,
        outcome.orders,
        promo.promo_flag,
        calendar.advent_flag,
        calendar.jan_dip_flag,
        calendar.spring_flag,
        calendar.schulbeginn_flag,
        calendar.summer_lull_flag,
        {% for channel in var('channel_taxonomy') %}
        coalesce(media_pivot.spend_{{ channel }}, 0.0) as spend_{{ channel }}{{ "," if not loop.last }}
        {% endfor %}
    from {{ ref('stg_outcome_weekly') }} as outcome
    inner join {{ ref('stg_promo') }} as promo
        on outcome.week_start = promo.week_start and outcome.layer = promo.layer
    inner join {{ ref('stg_calendar_weekly') }} as calendar
        on outcome.week_start = calendar.week_start
    left join media_pivot
        on outcome.week_start = media_pivot.week_start and outcome.layer = media_pivot.layer
)

-- Final select: exactly seventeen columns, in the binding 03_MODULES.md section 8 /
-- section 1.3 order. No `order by` -- table materialization does not guarantee
-- physical order; db.py's accessor (plan 03-07) and the export writer (plan 03-08)
-- assert ordering explicitly where it matters.
select
    cast(week_start as date) as week_start,
    cast(layer as varchar) as layer,
    cast(revenue as double) as revenue,
    cast(orders as bigint) as orders,
    cast(promo_flag as integer) as promo_flag,
    cast(advent_flag as integer) as advent_flag,
    cast(jan_dip_flag as integer) as jan_dip_flag,
    cast(spring_flag as integer) as spring_flag,
    cast(schulbeginn_flag as integer) as schulbeginn_flag,
    cast(summer_lull_flag as integer) as summer_lull_flag,
    {% for channel in var('channel_taxonomy') %}
    cast(spend_{{ channel }} as double) as spend_{{ channel }}{{ "," if not loop.last }}
    {% endfor %}
from base
